language: node_js

node_js:
 - '0.10'
 - '0.12'
 - '4'
 - '6'
 - '8'
 - '10'
 - 'stable'

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  - CXX=g++-4.8
